{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "59918f8e-56b9-4075-a94a-f04699205724",
   "metadata": {},
   "outputs": [],
   "source": [
    "streamlit_code = r'''\n",
    "import os\n",
    "import re\n",
    "import json\n",
    "import time\n",
    "import traceback\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import streamlit as st\n",
    "from langchain_ollama import OllamaLLM\n",
    "from sqlalchemy import create_engine, text\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  CONFIGURATION\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "OLLAMA_BASE_URL = \"http://localhost:11434\"\n",
    "LLM_MODEL = \"llama3.1\"\n",
    "\n",
    "# Default data source paths (can be changed in sidebar)\n",
    "DEFAULT_SQL_PATH = \"./data/sales.db\"\n",
    "DEFAULT_EXCEL_FILES = {\"employees\": \"./data/employees.xlsx\"}\n",
    "DEFAULT_CSV_FILES = {\"web_analytics\": \"./data/web_analytics.csv\"}\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  PAGE CONFIG\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "st.set_page_config(page_title=\"Data Metrics Agent\", page_icon=\"📊\", layout=\"wide\")\n",
    "st.title(\"📊 AI Data Metrics Agent\")\n",
    "st.caption(\"Ask questions about your data in plain English — powered by local Ollama\")\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  CACHED RESOURCES\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "@st.cache_resource\n",
    "def get_llm():\n",
    "    return OllamaLLM(model=LLM_MODEL, base_url=OLLAMA_BASE_URL, temperature=0.1)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  DATA SOURCE FUNCTIONS\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def get_sql_schema(engine) -> str:\n",
    "    with engine.connect() as conn:\n",
    "        tables = conn.execute(text(\n",
    "            \"SELECT name FROM sqlite_master WHERE type='table'\"\n",
    "        )).fetchall()\n",
    "        parts = []\n",
    "        for (table_name,) in tables:\n",
    "            cols = conn.execute(text(f\"PRAGMA table_info('{table_name}')\")).fetchall()\n",
    "            col_defs = \", \".join([f\"{c[1]} ({c[2]})\" for c in cols])\n",
    "            sample = conn.execute(text(f\"SELECT * FROM '{table_name}' LIMIT 2\")).fetchall()\n",
    "            parts.append(\n",
    "                f\"Table: {table_name}\\n  Columns: {col_defs}\\n  Sample: {sample}\"\n",
    "            )\n",
    "        return \"\\n\\n\".join(parts)\n",
    "\n",
    "\n",
    "def run_sql_query(engine, query: str) -> pd.DataFrame:\n",
    "    with engine.connect() as conn:\n",
    "        return pd.read_sql(query, conn)\n",
    "\n",
    "\n",
    "def get_file_info(files: dict, file_type: str) -> str:\n",
    "    parts = []\n",
    "    for name, path in files.items():\n",
    "        reader = pd.read_excel if file_type == \"excel\" else pd.read_csv\n",
    "        df = reader(path, nrows=3)\n",
    "        full_shape = reader(path).shape\n",
    "        cols = \", \".join([f\"{c} ({df[c].dtype})\" for c in df.columns])\n",
    "        parts.append(\n",
    "            f\"{file_type.title()} file: {name} ({path})\\n\"\n",
    "            f\"  Columns: {cols}\\n  Shape: {full_shape}\\n\"\n",
    "            f\"  Sample:\\n{df.head(2).to_string()}\"\n",
    "        )\n",
    "    return \"\\n\\n\".join(parts)\n",
    "\n",
    "\n",
    "def query_file(files: dict, file_key: str, pandas_code: str, file_type: str) -> pd.DataFrame:\n",
    "    if file_key not in files:\n",
    "        raise ValueError(f\"Unknown {file_type} file: {file_key}. Available: {list(files.keys())}\")\n",
    "    reader = pd.read_excel if file_type == \"excel\" else pd.read_csv\n",
    "    df = reader(files[file_key])\n",
    "    local_vars = {\"df\": df, \"pd\": pd, \"np\": np}\n",
    "    exec(f\"result = {pandas_code}\", {}, local_vars)\n",
    "    result = local_vars[\"result\"]\n",
    "    if isinstance(result, pd.Series):\n",
    "        result = result.to_frame()\n",
    "    elif not isinstance(result, pd.DataFrame):\n",
    "        result = pd.DataFrame({\"result\": [result]})\n",
    "    return result\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  CHART GENERATION\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def generate_chart(df: pd.DataFrame, plan: dict):\n",
    "    chart_type = plan.get(\"chart_type\", \"none\")\n",
    "    if chart_type == \"none\" or df.empty:\n",
    "        return None\n",
    "\n",
    "    if df.index.name or isinstance(df.index, pd.MultiIndex):\n",
    "        df = df.reset_index()\n",
    "\n",
    "    x_col = plan.get(\"chart_x\", df.columns[0])\n",
    "    y_col = plan.get(\"chart_y\", df.columns[-1] if len(df.columns) > 1 else df.columns[0])\n",
    "    title = plan.get(\"chart_title\", \"Query Result\")\n",
    "\n",
    "    if x_col not in df.columns:\n",
    "        x_col = df.columns[0]\n",
    "    if y_col not in df.columns:\n",
    "        y_col = df.columns[-1] if len(df.columns) > 1 else df.columns[0]\n",
    "\n",
    "    try:\n",
    "        if chart_type == \"bar\":\n",
    "            fig = px.bar(df, x=x_col, y=y_col, title=title, text_auto=True)\n",
    "        elif chart_type == \"line\":\n",
    "            fig = px.line(df, x=x_col, y=y_col, title=title, markers=True)\n",
    "        elif chart_type == \"pie\":\n",
    "            fig = px.pie(df, names=x_col, values=y_col, title=title)\n",
    "        elif chart_type == \"table\":\n",
    "            fig = go.Figure(data=[go.Table(\n",
    "                header=dict(values=list(df.columns), fill_color=\"#3b82f6\", font=dict(color=\"white\")),\n",
    "                cells=dict(values=[df[c] for c in df.columns], fill_color=\"#f1f5f9\"),\n",
    "            )])\n",
    "            fig.update_layout(title=title)\n",
    "        else:\n",
    "            return None\n",
    "\n",
    "        fig.update_layout(template=\"plotly_white\", height=400, margin=dict(l=40, r=40, t=60, b=40))\n",
    "        return fig\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  AGENT LOGIC\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "def build_schema_context(sql_engine, excel_files, csv_files) -> str:\n",
    "    parts = [\"=== AVAILABLE DATA SOURCES ===\"]\n",
    "    if sql_engine:\n",
    "        parts.append(\"\\n--- SQL DATABASE (source_type: sql) ---\")\n",
    "        parts.append(get_sql_schema(sql_engine))\n",
    "    if excel_files:\n",
    "        parts.append(\"\\n--- EXCEL FILES (source_type: excel) ---\")\n",
    "        parts.append(get_file_info(excel_files, \"excel\"))\n",
    "    if csv_files:\n",
    "        parts.append(\"\\n--- CSV FILES (source_type: csv) ---\")\n",
    "        parts.append(get_file_info(csv_files, \"csv\"))\n",
    "    return \"\\n\".join(parts)\n",
    "\n",
    "\n",
    "def get_routing_prompt(question: str, schema_context: str, history: list) -> str:\n",
    "    history_text = \"\"\n",
    "    if history:\n",
    "        recent = history[-6:]\n",
    "        history_text = \"\\n--- Recent conversation ---\\n\"\n",
    "        for h in recent:\n",
    "            history_text += f\"{h['role'].upper()}: {h['content']}\\n\"\n",
    "\n",
    "    return f\"\"\"You are a data analytics agent. Given the user's question and the\n",
    "available data sources below, do the following:\n",
    "\n",
    "1. Determine which data source to query (sql, excel, or csv).\n",
    "2. Write the exact query to answer the question.\n",
    "3. Specify what chart type would best visualize the result.\n",
    "\n",
    "{schema_context}\n",
    "{history_text}\n",
    "\n",
    "USER QUESTION: {question}\n",
    "\n",
    "Respond in EXACTLY this JSON format (no extra text, no markdown):\n",
    "{{\n",
    "  \"source_type\": \"sql\" | \"excel\" | \"csv\",\n",
    "  \"file_key\": \"<file key for excel/csv, or empty for sql>\",\n",
    "  \"query\": \"<SQL query for sql, or pandas expression for excel/csv>\",\n",
    "  \"chart_type\": \"bar\" | \"line\" | \"pie\" | \"table\" | \"none\",\n",
    "  \"chart_x\": \"<column for x-axis>\",\n",
    "  \"chart_y\": \"<column for y-axis>\",\n",
    "  \"chart_title\": \"<chart title>\"\n",
    "}}\n",
    "\n",
    "RULES:\n",
    "- For sql: write valid SQLite SQL.\n",
    "- For excel/csv: write a valid pandas expression using 'df'. Must return DataFrame or Series.\n",
    "- Pick the best chart type for the result shape.\n",
    "- Use \"table\" for multi-column detail, \"none\" for single numbers.\n",
    "\n",
    "JSON response:\"\"\"\n",
    "\n",
    "\n",
    "def parse_llm_response(response: str) -> dict:\n",
    "    response = response.strip()\n",
    "    response = re.sub(r\"```json\\s*\", \"\", response)\n",
    "    response = re.sub(r\"```\\s*\", \"\", response)\n",
    "    match = re.search(r\"\\{[^{}]*\\}\", response, re.DOTALL)\n",
    "    if match:\n",
    "        return json.loads(match.group())\n",
    "    raise ValueError(f\"Could not parse LLM response as JSON.\")\n",
    "\n",
    "\n",
    "def process_question(question, llm, sql_engine, excel_files, csv_files, schema_context, history):\n",
    "    # Step 1: Route\n",
    "    prompt = get_routing_prompt(question, schema_context, history)\n",
    "    raw = llm.invoke(prompt)\n",
    "    plan = parse_llm_response(raw)\n",
    "\n",
    "    # Step 2: Execute\n",
    "    source = plan[\"source_type\"]\n",
    "    if source == \"sql\":\n",
    "        result_df = run_sql_query(sql_engine, plan[\"query\"])\n",
    "    elif source == \"excel\":\n",
    "        result_df = query_file(excel_files, plan[\"file_key\"], plan[\"query\"], \"excel\")\n",
    "    elif source == \"csv\":\n",
    "        result_df = query_file(csv_files, plan[\"file_key\"], plan[\"query\"], \"csv\")\n",
    "    else:\n",
    "        raise ValueError(f\"Unknown source: {source}\")\n",
    "\n",
    "    # Step 3: Explain\n",
    "    explain_prompt = f\"\"\"Based on this data result, answer the user's question clearly.\n",
    "Include key numbers. Be concise (2-4 sentences).\n",
    "\n",
    "Question: {question}\n",
    "Source: {source}\n",
    "Result:\n",
    "{result_df.to_string(max_rows=20)}\n",
    "\n",
    "Answer:\"\"\"\n",
    "    explanation = llm.invoke(explain_prompt)\n",
    "\n",
    "    return plan, result_df, explanation\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  SIDEBAR — Data Source Configuration\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "with st.sidebar:\n",
    "    st.header(\"🔗 Data Sources\")\n",
    "\n",
    "    # SQL\n",
    "    st.subheader(\"SQL Database\")\n",
    "    sql_path = st.text_input(\"SQLite DB path\", value=DEFAULT_SQL_PATH)\n",
    "    sql_engine = None\n",
    "    if sql_path and os.path.exists(sql_path):\n",
    "        sql_engine = create_engine(f\"sqlite:///{sql_path}\")\n",
    "        st.success(f\"Connected: {sql_path}\")\n",
    "    elif sql_path:\n",
    "        st.warning(\"DB file not found\")\n",
    "\n",
    "    # Excel\n",
    "    st.subheader(\"Excel Files\")\n",
    "    excel_input = st.text_area(\n",
    "        \"Name=Path (one per line)\",\n",
    "        value=\"\\n\".join([f\"{k}={v}\" for k, v in DEFAULT_EXCEL_FILES.items()]),\n",
    "        height=68,\n",
    "    )\n",
    "    excel_files = {}\n",
    "    for line in excel_input.strip().split(\"\\n\"):\n",
    "        if \"=\" in line:\n",
    "            k, v = line.split(\"=\", 1)\n",
    "            if os.path.exists(v.strip()):\n",
    "                excel_files[k.strip()] = v.strip()\n",
    "    if excel_files:\n",
    "        st.success(f\"{len(excel_files)} Excel file(s)\")\n",
    "\n",
    "    # CSV\n",
    "    st.subheader(\"CSV Files\")\n",
    "    csv_input = st.text_area(\n",
    "        \"Name=Path (one per line)\",\n",
    "        value=\"\\n\".join([f\"{k}={v}\" for k, v in DEFAULT_CSV_FILES.items()]),\n",
    "        height=68,\n",
    "    )\n",
    "    csv_files = {}\n",
    "    for line in csv_input.strip().split(\"\\n\"):\n",
    "        if \"=\" in line:\n",
    "            k, v = line.split(\"=\", 1)\n",
    "            if os.path.exists(v.strip()):\n",
    "                csv_files[k.strip()] = v.strip()\n",
    "    if csv_files:\n",
    "        st.success(f\"{len(csv_files)} CSV file(s)\")\n",
    "\n",
    "    st.divider()\n",
    "    st.caption(f\"**Model:** {LLM_MODEL}\")\n",
    "\n",
    "    if st.button(\"🗑️ Clear Chat\", use_container_width=True):\n",
    "        st.session_state[\"messages\"] = []\n",
    "        st.session_state[\"agent_history\"] = []\n",
    "        st.rerun()\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  BUILD SCHEMA CONTEXT\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "schema_context = build_schema_context(sql_engine, excel_files, csv_files)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "#  CHAT INTERFACE\n",
    "# ══════════════════════════════════════════════════════════════\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state[\"messages\"] = []\n",
    "if \"agent_history\" not in st.session_state:\n",
    "    st.session_state[\"agent_history\"] = []\n",
    "\n",
    "# Display chat history\n",
    "for msg in st.session_state[\"messages\"]:\n",
    "    with st.chat_message(msg[\"role\"]):\n",
    "        st.markdown(msg[\"content\"])\n",
    "        if msg.get(\"chart\"):\n",
    "            st.plotly_chart(msg[\"chart\"], use_container_width=True)\n",
    "        if msg.get(\"data\") is not None:\n",
    "            with st.expander(\"📋 Raw Data\"):\n",
    "                st.dataframe(msg[\"data\"], use_container_width=True)\n",
    "        if msg.get(\"plan\"):\n",
    "            with st.expander(\"🔍 Query Details\"):\n",
    "                st.json(msg[\"plan\"])\n",
    "\n",
    "# Chat input\n",
    "if prompt := st.chat_input(\"Ask about your data... (e.g., 'What is total revenue by region?')\"):\n",
    "    st.session_state[\"messages\"].append({\"role\": \"user\", \"content\": prompt})\n",
    "    st.session_state[\"agent_history\"].append({\"role\": \"user\", \"content\": prompt})\n",
    "\n",
    "    with st.chat_message(\"user\"):\n",
    "        st.markdown(prompt)\n",
    "\n",
    "    with st.chat_message(\"assistant\"):\n",
    "        with st.spinner(\"Analyzing your data...\"):\n",
    "            try:\n",
    "                start = time.time()\n",
    "                plan, result_df, explanation = process_question(\n",
    "                    prompt, get_llm(), sql_engine, excel_files, csv_files,\n",
    "                    schema_context, st.session_state[\"agent_history\"]\n",
    "                )\n",
    "                elapsed = time.time() - start\n",
    "\n",
    "                # Display explanation\n",
    "                st.markdown(explanation)\n",
    "\n",
    "                # Display chart\n",
    "                fig = generate_chart(result_df, plan)\n",
    "                if fig:\n",
    "                    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "                # Raw data expander\n",
    "                with st.expander(\"📋 Raw Data\"):\n",
    "                    st.dataframe(result_df, use_container_width=True)\n",
    "\n",
    "                # Query details expander\n",
    "                with st.expander(\"🔍 Query Details\"):\n",
    "                    st.json(plan)\n",
    "\n",
    "                st.caption(f\"⏱️ {elapsed:.2f}s | Source: {plan['source_type']}\")\n",
    "\n",
    "                # Save to history\n",
    "                st.session_state[\"messages\"].append({\n",
    "                    \"role\": \"assistant\",\n",
    "                    \"content\": explanation,\n",
    "                    \"chart\": fig,\n",
    "                    \"data\": result_df,\n",
    "                    \"plan\": plan,\n",
    "                })\n",
    "                st.session_state[\"agent_history\"].append(\n",
    "                    {\"role\": \"assistant\", \"content\": explanation}\n",
    "                )\n",
    "\n",
    "            except Exception as e:\n",
    "                error_msg = f\"Sorry, I ran into an error: {str(e)}\"\n",
    "                st.error(error_msg)\n",
    "                with st.expander(\"Traceback\"):\n",
    "                    st.code(traceback.format_exc())\n",
    "                st.session_state[\"messages\"].append(\n",
    "                    {\"role\": \"assistant\", \"content\": error_msg}\n",
    "                )\n",
    "'''\n",
    "\n",
    "with open(\"app.py\", \"w\", encoding=\"utf-8\") as f:\n",
    "    f.write(streamlit_code.strip())\n",
    "\n",
    "print(\"✅ Streamlit app written to 'app.py'\")\n",
    "print(\"\\n🚀 To launch:\")\n",
    "print(\"   streamlit run app.py\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
